language: cpp

compiler:
- gcc

os:
- linux

branches:

  only:
  - master
  - ApplicationServer

before_script:
  - mkdir build
  - cd build

script:
  - c++ ApplicationServer/code/main.cpp -o main
  - ./main
